#!/bin/bash
#============================== SUMMARY =====================================
#
#Program : check_galera_state
#Version : 0.1
#Date    : Oct 14, 2015
#Author  : Mario Hernandez - @mariofix
#Licence : GPL - summary below, full text at http://www.fsf.org/licenses/gpl.txt
#Requirements: mariadb, galera
#
#
# =========================== PROGRAM LICENSE =================================
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

state=`echo "show status like 'wsrep_local_state';" | mysql -u sticbkp | egrep -v 'gcomm|Value' | awk '{print $2}'`

if [ $state -eq 1 ]
then
    echo "WARNING - Estado Joining"
    exit 1
elif [ $state -eq 2 ]
then
    echo "CRITICAL - Estado Donor/Desynced"
    exit 2
elif [ $state -eq 3 ]
then
    echo "WARNING - Estado Joined"
    exit 1
elif [ $state -eq 4 ]
then
    echo "OK - Synced"
    exit 0
else
    echo "CRITICAL - $state"
    exit 2
fi
